config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: "tasks#index"
  resources:tasks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence: true
  validates :email,presence: true,uniqueness: true
  has_secure_password
  validates :password,presence: true,length: {minimum: 4}
  has_many:tasks
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "ユーザーを作成しました。"
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to admin_users_path
   else
     render "edit"
   end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "ユーザーを削除しました。"
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def authenticate_user
    @current_user = current_user
    if @current_user == nil
      flash[:notice] = "ログインをしてください。"
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:notice] = "ログインに失敗しました。"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました。"
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate_user

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    if @task.save
      flash[:notice]= "新規登録しました！"
      redirect_to tasks_path
    else
      render "new"
    end
  end

  def index


    else
      @tasks = Task.all.order(created_at: "DESC").page(params[:page])

    end
  end

  def search
    if params[:task][:name].present? && params[:task][:status].present?
      @tasks = Task.name_status_search(params[:task][:name], params[:task][:status])
      flash[:notice] = "タイトルとステータスで絞り込みました。"
      render "index"
    elsif params[:task][:name].present?
      @tasks = Task.name_search(params[:task][:name])
      flash[:notice] = "タイトルで絞り込みました。"
      render "index"
    elsif params[:task][:status].present?
      @tasks = Task.status_search(params[:task][:status])
      flash[:notice] = "ステータスで絞り込みました。"
      render "index"
    else
      @tasks = Task.all
      flash[:notice] = "検索項目を入力してください。"
      render "index"
    end
  end


  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    flash[:notice]= "編集しました！"
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice]= "削除しました！"
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name,:content,:expired_date,:status,:priority)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h4>ユーザー編集画面</h4>
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %><br>
  <% end %>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.label :password %>(※4文字以上)<br>
  <%= f.text_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.text_field :password_confirmation %><br>
  <%= f.label :role_admin %>
  <%= f.check_box :admin, :as => :boolean %><br>
  <%= f.submit "作成する", name: "admin" %><br>
<% end %>

<%= link_to "ユーザー一覧", admin_users_path %>

app/views/admin/users/index.html.erb
<h3>管理ユーザー画面だよ</h3>
<%= link_to "ユーザーの新規作成", new_admin_user_path %><br><br>
<%= notice %><br>
<% @users.each do |user|%>
<%= user.id %>
<%= user.name %>
<%= user.tasks.count %>
<%= user.admin %>
<%= link_to "タスク詳細", admin_user_path(user.id) %>
<%= link_to "編集", edit_admin_user_path(user.id) %>
<%= link_to "削除", admin_user_path(user.id), method: :delete, data:{confirm: "本当に削除していいですか？"} %><br>
<% end %>

app/views/admin/users/new.html.erb
<h4>ユーザー作成画面</h4>
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %><br>
  <% end %>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.label :password %>(※4文字以上)<br>
  <%= f.text_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.text_field :password_confirmation %><br>
  <%= f.label :role_admin %>
  <%= f.check_box :admin, :as => :boolean %><br>

  <%= f.submit "作成する", name: "admin" %><br>
<% end %>

<%= link_to "ユーザー一覧", admin_users_path %>

app/views/admin/users/show.html.erb
<%= @user.name%>さんのタスク<br><br>

<% @user.tasks.each do |task|%>
名前
<%= task.name %><br>
内容
<%= task.content %><br><br>
<% end %><br>

<%= link_to "ユーザー一覧", admin_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if logged_in? %>
    <%= link_to "プロフィール", user_path(current_user.id) %>
    <%= link_to "ログアウト", session_path(current_user.id),method: :delete %><br>
  <% else %>
    <%= link_to "新規登録", new_user_path %>
    <%= link_to "ログイン", new_session_path %><br>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<ul class="list-group">
  <li class="list-group-item">
<h3><%= image_tag('/assets/111.png') %>編集</h3></li>
<%= form_with(model: @task, local: true) do |form|%>
  <li class="list-group-item">
<%= form.label :name %><br>
<%= form.text_field :name %><br></li>
  <li class="list-group-item">
<%= form.label :content %><br>
<%= form.text_area :content %><br></li>
  <li class="list-group-item">
<%= form.label :expired_date %><br>
<%= form.date_field :expired_date %><br></li>
  <li class="list-group-item">
<%= form.label :status %>: <%= form.select :status, Task.statuses.keys, {waiting:'waiting',working:'working',completed:'completed'} %><br></li>
  <li class="list-group-item">
<%= form.label :priority %>: <%= form.select :priority, Task.priorities.keys,
{high:'high',middle:'middle',low:'low'}%><br></li>

  <li class="list-group-item">
<%= form.submit t('view.submit') %><br></li>
<% end %>
</ul>
　<%= link_to t('view.index'), tasks_path %>

app/views/tasks/index.html.erb
<h3><%= current_user.name %>さん<br>
  タスク<%= t('view.index')%></h3>
<%= notice %><br>

<%= link_to "新着順にする", tasks_path %><br>
<%= link_to "終了期限順にする", tasks_path(sort_expired: "true") %><br>
<%= link_to "優先順位順にする", tasks_path(sort_priority: "true") %>

<% @tasks.each do |task| %>
<% if task.user_id == current_user.id %>
　<div class="list-group">
  <a href="#" class="list-group-item active">
  <%= t('view.name')%>: <%= task.name %><br></a>
  <a href="#" class="list-group-item">
  <%= t('view.content')%>: <%= task.content %><br></a>
  <a href="#" class="list-group-item">
  期限: <%= task.expired_date %>
  　状態: <%= task.status %>
  　優先順位: <%= task.priority %></a>
  　<%= link_to t('view.edit'),edit_task_path(task.id) %>
  <%= link_to t('view.show'), task_path(task.id) %>
  <%= link_to t('view.destroy'), task_path(task.id), method: :delete, data:{ confirm: "本当に削除していいですか？"} %>
  </div>
<% else %>
<% end %>
<% end %>
　<%= paginate @tasks %>

app/views/tasks/show.html.erb
<h3><%= t('view.show')%></h3><br>
<div class="list-group">
  <a href="#" class="list-group-item active">
  <%= t('view.name')%>: <%= @task.name %><br></a>
  <a href="#" class="list-group-item">
  <%= t('view.content')%>: <%= @task.content %><br></a>
  <a href="#" class="list-group-item">
  期限: <%= @task.expired_date %>
  　状態: <%= @task.status %>
  　優先順位: <%= @task.priority %></a>
</div>
　<%= link_to t('view.index'), tasks_path %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %><br>
  <% end %>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.label :password %>(※4文字以上)<br>
  <%= f.text_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.text_field :password_confirmation %><br>
  <%= f.submit "登録する"%><br>

<% end %>

app/views/users/show.html.erb
<h4><%= @user.name%>のページです。</h4><br>

<h4><%= @user.email%></h4>

<%= link_to "タスクを見る",tasks_path %>